name: dart_banco_dados
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mysql1: ^0.19.2  

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
